clear all; clc;
addpath('C:\ResearchFile\casadi-windows-matlabR2016a-v3.5.5\')
import casadi.*

%%
warning off
clc;
load_config; % define the mass and inertia here
cons_list = {}; % for constrained systems, define the dimensions and the constraint functions here.

%% Dynamics of a single step (full SE(3) x SE(3) version)
dim_u = 6;
vars = gen_SO3xR3_Variables(cons_list, inertial_list, dim_u); % keep original helper name for compatibility

% tau_f = B * vars.u;

% State is interpreted as two SE(3) blocks:
%   X = (R, p)
%   G = (F, v)
% Equality constraints are generated by the corrected local second-order
% model in gen_SE3_EqualityConstraints.
input_map = [zeros(6, 1);
             vars.u];

[eq_eps, eq_terminal_eps] = gen_SE3_EqualityConstraints_v2(vars, cons_list, inertial_list, g, input_map);

%% State for all steps
x   = SX.sym('x',   [24 * size(vars, 2), Ns + 1]);
u   = SX.sym('u',   [dim_u, Ns]);
lam = SX.sym('lam', [12 * size(vars.lam, 2), Ns]);

y = SX.sym('y', [size(vars.nu, 1), Ns + 1]);

% perturbations
ex   = SX.sym('ex',   [12 * size(vars.emat, 2), Ns + 1]);
eu   = SX.sym('eu',   [dim_u * size(vars.eu, 2), Ns]);
elam = SX.sym('elam', [12 * size(vars.elam, 2) * 0, Ns]);
ey   = SX.sym('ey',   size(y));

dt = SX.sym('dt', [Ns]);

Lagrangian = 0;

%% The retraction map: SE(3) on both [R,p] and [F,v]
x_new = [];
for k = 1:Ns + 1
    Rk = x(1:9, k);   Rk = reshape(Rk, [3, 3]);
    pk = x(10:12, k);
    Fk = x(13:21, k); Fk = reshape(Fk, [3, 3]);
    vk = x(22:24, k);

    [Rk_new, pk_new] = Retract_SE3_Left(Rk, pk, ex(1:3, k), ex(4:6, k));
    [Fk_new, vk_new] = Retract_SE3_Left(Fk, vk, ex(7:9, k), ex(10:12, k));

    xk_new = [Rk_new(:);
              pk_new(:);
              Fk_new(:);
              vk_new(:)];

    x_new = [x_new, xk_new];
end

y_new = y + ey;
u_new = u + eu;

%% The following code generate the Lagrangian:
[SE3_cost, vars_cost] = gen_SE3_trace_cost();
% [SE3_cost, vars_cost] = gen_SO3xR3_trace_cost();

% terminal cost
QRt = SX.sym('QRt', 3, 3);
QFt = SX.sym('QFt', 3, 3);
Qpt = SX.sym('Qpt', 3, 3);
Qvt = SX.sym('Qvt', 3, 3);

xd = SX.sym('xd', [24 * size(vars, 2), Ns + 1]);
ud = SX.sym('ud', [dim_u, Ns]);

Rcontrol = SX.sym('R', [dim_u, dim_u]);
for k = 1:Ns + 1
    ck = substitute(SE3_cost, vars_cost.x,  x(:, k));
    ck = substitute(ck, vars_cost.xd, xd(:, k));
    ck = substitute(ck, vars_cost.e,  ex(:, k));

    if k == Ns + 1
        ck = substitute(ck, vars_cost.QR, QRt);
        ck = substitute(ck, vars_cost.Qp, Qpt);
        ck = substitute(ck, vars_cost.QF, QFt);
        ck = substitute(ck, vars_cost.Qv, Qvt);
    else
        du = (u(:, k) + eu(:, k) - ud(:, k));
        ck = ck + 1 / 2 * du' * Rcontrol * du;
    end

    Lagrangian = Lagrangian + ck;
end

Cost = Lagrangian;

%% Dynamics constraints in the Lagrangian
eq_all = [];
for k = 1:Ns
    eq_k = substitute(eq_eps, vars.emat, [ex(:, k); ex(:, k + 1)]);
    eq_k = substitute(eq_k, vars.eu,   eu(:, k));
    eq_k = substitute(eq_k, vars.elam, elam(:, k));

    eq_k = substitute(eq_k, vars.xmat, [x(:, k); x(:, k + 1)]);
    eq_k = substitute(eq_k, vars.u,    u(:, k));
    eq_k = substitute(eq_k, vars.dt,   dt(k));
    
    % if k == 1
        % eq_all = [eq_all; zeros(12, 1)];
    % else
        eq_all = [eq_all; eq_k];
    % end
    Lagrangian = Lagrangian + sum(eq_k .* y(:, k + 1));
end

%% Inequality constraints in the Lagrangian
ieq_all = [];
dim_ieq = 12;
z  = SX.sym('z', [dim_ieq, Ns]);
s  = SX.sym('s', size(z));
ez = SX.sym('ez', [dim_ieq, Ns]);
es = SX.sym('es', size(z));

for k = 1:Ns
    ieq_k = [(u(:, k) + eu(:, k)) - 3;
            -(u(:, k) + eu(:, k)) - 3];

    ieq_all = [ieq_all; ieq_k + s(:, k)];
    Lagrangian = Lagrangian + sum(ieq_k .* z(:, k));
end

z_new = z + ez;
s_new = s + es;

%% Initial constraints
x0 = SX.sym('x0', [24, 1]);

R0 = reshape(x0(1:9),   [3, 3]);
p0 = x0(10:12);
F0 = reshape(x0(13:21), [3, 3]);
v0 = x0(22:24);

R1 = reshape(x(1:9, 1),   [3, 3]);
p1 = x(10:12, 1);
F1 = reshape(x(13:21, 1), [3, 3]);
v1 = x(22:24, 1);

% [R1e, p1e] = Retract_SE3_Left(R1, p1, ex(1:3, 1), ex(4:6, 1));
% [F1e, v1e] = Retract_SE3_Left(F1, v1, ex(7:9, 1), ex(10:12, 1));
% [F0s, v0s] = deal(F0, v0);

[R0inv, p0inv] = Inv_SE3(R0, p0);
[Req0, peq0] = Mul_SE3(R0inv, p0inv, R1, p1);

[F0inv, v0inv] = Inv_SE3(F0, v0);
[Feq0, veq0] = Mul_SE3(F0inv, v0inv, F1, v1);

eq_0 = [Log_SE3_pair(Req0, peq0);
        Log_SE3_pair(Feq0, veq0)] + ex(1:12, 1);

% eq_0 = [Log_SE3_pair(Req0, peq0);
%         Log_SE3_pair(Feq0, veq0)];
% 
% eq_0 = zeros(12, 1);

eq_all = [eq_0; eq_all];
Lagrangian = Lagrangian + sum(eq_0 .* y(:, 1));
% 
% eq_all = [zeros(12, 1); eq_all];
% Lagrangian = Lagrangian + sum(eq_0 .* y(:, 1));

vars_kkt = [ex(:); eu(:); y(:); z(:); s(:)];
mu = SX.sym('mu', 1);

%% KKT vector field and its Jacobians
b = [jacobian(Lagrangian, [ex(:); eu(:)])';
     eq_all;
     ieq_all;
     s(:) .* z(:) - mu];

A = jacobian(b, vars_kkt);

f  = substitute(Cost, [ex(:); eu(:)], [ex(:); eu(:)] * 0);
df = jacobian(Cost, [ex(:); eu(:)]);
df = substitute(df, [ex(:); eu(:)], [ex(:); eu(:)] * 0);
b  = substitute(b, [ex(:); eu(:)], [ex(:); eu(:)] * 0);
A  = substitute(A, [ex(:); eu(:)], [ex(:); eu(:)] * 0);

len_sym = length(ex(:)) + length(eu(:)) + length(y(:)) + length(z(:));

A = A + speye(size(A, 1)) * 1e-2;
A = A - speye(size(A, 1)) * 1e-2;

h = substitute(eq_all, [ex(:); eu(:)], [ex(:); eu(:)] * 0);
g = substitute(ieq_all, [ex(:); eu(:)], [ex(:); eu(:)] * 0);
g = substitute(g, s(:), s(:) * 0);

A_sym = A(1:len_sym, 1:len_sym);
A_sym(end-length(s(:)) + 1:end, end-length(s(:)) + 1:end) = -diag(s(:) ./ z(:));
A_sym = triu(A_sym);

Qstage = [vars_cost.QR(:);
          vars_cost.Qp(:);
          vars_cost.QF(:);
          vars_cost.Qv(:)];
Qterminal = [QRt(:);
             Qpt(:);
             QFt(:);
             Qvt(:)];

opts = struct('main', true, 'mex', true);

xu = [x(:); u(:)];

%% generate the util functions
fun_b = Function('b_kkt_mex', {xu, y(:), z(:), s(:), mu, x0, Qstage, Qterminal, Rcontrol(:), xd(:), ud(:), dt(:)}, {b});
fun_b.generate('b_kkt_mex.c', opts);

fun_Asym = Function('Asym_kkt', {xu, y(:), z(:), s(:), mu, x0, Qstage, Qterminal, Rcontrol(:), xd(:), ud(:), dt(:)}, {A_sym});
fun_Asym.generate('Asym_kkt_mex.c', opts);

% fun_A = Function('A_kkt_mex', {xu, y(:), z(:), s(:), mu, x0, Qstage, Qterminal, Rcontrol(:), xd(:), ud(:), dt(:)}, {A});
% fun_A.generate('A_kkt_mex.c', opts);

fun_f = Function('f_mex', {xu, y(:), z(:), s(:), mu, x0, Qstage, Qterminal, Rcontrol(:), xd(:), ud(:), dt(:)}, {f});
fun_f.generate('f_mex.c', opts);

fun_df = Function('df_mex', {xu, y(:), z(:), s(:), mu, x0, Qstage, Qterminal, Rcontrol(:), xd(:), ud(:), dt(:)}, {df});
fun_df.generate('df_mex.c', opts);

fun_hg = Function('hg_mex', {xu, y(:), z(:), s(:), mu, x0, Qstage, Qterminal, Rcontrol(:), xd(:), ud(:), dt(:)}, {h, g});
fun_hg.generate('hg_mex.c', opts);

xu_new = [x_new(:); u_new(:)];
fun_retract = Function('Retraction_xyz', ...
                       {xu, y(:), z(:), s(:), [ex(:); eu(:); ey(:); ez(:); es(:)]}, ...
                       {xu_new, y_new(:), z_new(:), s_new(:)});
fun_retract.generate('Retraction_xyz_mex.c', opts);

%%
c_files = dir('*.c');
parfor k = 1:length(c_files)
    try
        mex(c_files(k).name);
    catch ME
        warning('Failed to compile %s: %s', c_files(k).name, ME.message);
    end
end

%%
output_dir = "gen_casadi";
movefile('*.c', output_dir);
movefile('*.mex*', output_dir);

%% the following are for the cpp applications outside of MATLAB
import casadi.*
output_dir = "gen_casadi_cpp";
opts = struct('with_header', true);

xu = [x(:); u(:)];

fun_b = Function('b_kkt', {xu, y(:), z(:), s(:), mu, x0, Qstage, Qterminal, Rcontrol(:), xd(:), ud(:), dt(:)}, {b});
fun_b.generate('b_kkt.cpp', opts);

fun_A = Function('A_kkt', {xu, y(:), z(:), s(:), mu, x0, Qstage, Qterminal, Rcontrol(:), xd(:), ud(:), dt(:)}, {A});
fun_A.generate('A_kkt.cpp', opts);

fun_Asym = Function('Asym_kkt', {xu, y(:), z(:), s(:), mu, x0, Qstage, Qterminal, Rcontrol(:), xd(:), ud(:), dt(:)}, {A_sym});
fun_Asym.generate('Asym_kkt.cpp', opts);

fun_f = Function('f', {xu, y(:), z(:), s(:), mu, x0, Qstage, Qterminal, Rcontrol(:), xd(:), ud(:), dt(:)}, {f});
fun_f.generate('f.cpp', opts);

fun_df = Function('df', {xu, y(:), z(:), s(:), mu, x0, Qstage, Qterminal, Rcontrol(:), xd(:), ud(:), dt(:)}, {df});
fun_df.generate('df.cpp', opts);

fun_hg = Function('hg', {xu, y(:), z(:), s(:), mu, x0, Qstage, Qterminal, Rcontrol(:), xd(:), ud(:), dt(:)}, {h, g});
fun_hg.generate('hg.cpp', opts);

xu_new = [x_new(:); u_new(:)];
fun_retract = Function('Retraction_xyz', ...
                       {xu, y(:), z(:), s(:), [ex(:); eu(:); ey(:); ez(:); es(:)]}, ...
                       {xu_new, y_new(:), z_new(:), s_new(:)});
fun_retract.generate('Retraction_xyz.cpp', opts);

movefile('*.cpp', output_dir);
movefile('*.h', output_dir);

%% =========================================================================
function [Rnew, pnew] = Retract_SE3_Left(R, p, phi, rho)
J = LeftJacobian_SO3(phi);
Rnew = R * Exp_SO3_Rodriguez(phi);
pnew = p + R * J * rho;
end

function [R3, p3] = Mul_SE3(R1, p1, R2, p2)
R3 = R1 * R2;
p3 = p1 + R1 * p2;
end

function [Rinv, pinv] = Inv_SE3(R, p)
Rinv = R';
pinv = -R' * p;
end

function xi = Log_SE3_pair(R, p)
phi = Log_SO3(R);
Jinv = LeftJacobianInv_SO3(phi);
rho = Jinv * p;
xi = [phi; rho];
end

function J = LeftJacobian_SO3(phi)
tt = sqrt(sum(phi.^2) + 1e-6);
phihat = skew_SO3(phi);
A = (1 - cos(tt)) / (tt^2 + 1e-8);
B = (tt - sin(tt)) / (tt^3 + 1e-8);
J = eye(3) + A * phihat + B * (phihat * phihat);
end

function Jinv = LeftJacobianInv_SO3(phi)
tt = sqrt(sum(phi.^2) + 1e-6);
phihat = skew_SO3(phi);
A = 1 / (tt^2 + 1e-8) - (1 + cos(tt)) / (2 * tt * sin(tt) + 1e-8);
Jinv = eye(3) - 0.5 * phihat + A * (phihat * phihat);
end

function w = Log_SO3(R)

t = (trace(R) - 1)/2;
t = if_else(t < -1, -1, t);
t = if_else(t >  1,  1, t);
t = acos( t );
w = t / 2 / sin( sqrt(abs(t^2) + 1e-6) ) * [R(3, 2) - R(2, 3);
                           R(1, 3) - R(3, 1);
                           R(2, 1) - R(1, 2)];
end

% function w = Log_SO3(R)
% t = (trace(R) - 1) / 2;
% t = if_else(t < -1, -1, t);
% t = if_else(t >  1,  1, t);
% t = acos(t);
% w = t / (2 * sin(sqrt(abs(t^2) + 1e-6))) * ...
%     [R(3, 2) - R(2, 3);
%      R(1, 3) - R(3, 1);
%      R(2, 1) - R(1, 2)];
% end

% function R = Exp_SO3_Rodriguez(t)
% tt = sqrt(sum(t.^2) + 1e-6);
% K = skew_SO3(t);
% R = eye(3) + sin(tt) / tt * K + (1 - cos(tt)) / (tt^2) * (K * K);
% end

function R = Exp_SO3_Rodriguez(t)
tt = sqrt(sum(t.^2) + 1e-6);
R = eye(3) + sin(tt) / tt * skew_SO3(t) + ...
      (1 - cos(tt)) / (tt^2) * skew_SO3(t)^2;
end


% function R = Exp_SO3_Rodriguez(t)
% tt2 = sum(t.^2);
% K = skew_SO3(t);
% 
% A = if_else(tt2 < 1e-6, 1 - tt2/6 + tt2^2/120, sin(sqrt(tt2))/sqrt(tt2));
% B = if_else(tt2 < 1e-6, 1/2 - tt2/24 + tt2^2/720, (1 - cos(sqrt(tt2)))/tt2);
% 
% R = eye(3) + A * K + B * (K * K);
% end

% function S = skew_SO3(w)
% S = [    0, -w(3),  w(2);
%       w(3),     0, -w(1);
%      -w(2),  w(1),     0];
% end
