/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int hg(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int hg_alloc_mem(void);
int hg_init_mem(int mem);
void hg_free_mem(int mem);
int hg_checkout(void);
void hg_release(int mem);
void hg_incref(void);
void hg_decref(void);
casadi_int hg_n_out(void);
casadi_int hg_n_in(void);
casadi_real hg_default_in(casadi_int i);
const char* hg_name_in(casadi_int i);
const char* hg_name_out(casadi_int i);
const casadi_int* hg_sparsity_in(casadi_int i);
const casadi_int* hg_sparsity_out(casadi_int i);
int hg_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
