/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int A_kkt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int A_kkt_alloc_mem(void);
int A_kkt_init_mem(int mem);
void A_kkt_free_mem(int mem);
int A_kkt_checkout(void);
void A_kkt_release(int mem);
void A_kkt_incref(void);
void A_kkt_decref(void);
casadi_int A_kkt_n_out(void);
casadi_int A_kkt_n_in(void);
casadi_real A_kkt_default_in(casadi_int i);
const char* A_kkt_name_in(casadi_int i);
const char* A_kkt_name_out(casadi_int i);
const casadi_int* A_kkt_sparsity_in(casadi_int i);
const casadi_int* A_kkt_sparsity_out(casadi_int i);
int A_kkt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
