/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int Retraction_xyz(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int Retraction_xyz_alloc_mem(void);
int Retraction_xyz_init_mem(int mem);
void Retraction_xyz_free_mem(int mem);
int Retraction_xyz_checkout(void);
void Retraction_xyz_release(int mem);
void Retraction_xyz_incref(void);
void Retraction_xyz_decref(void);
casadi_int Retraction_xyz_n_out(void);
casadi_int Retraction_xyz_n_in(void);
casadi_real Retraction_xyz_default_in(casadi_int i);
const char* Retraction_xyz_name_in(casadi_int i);
const char* Retraction_xyz_name_out(casadi_int i);
const casadi_int* Retraction_xyz_sparsity_in(casadi_int i);
const casadi_int* Retraction_xyz_sparsity_out(casadi_int i);
int Retraction_xyz_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
