function J2Jd = fun_J2Jd(in1)
%fun_J2Jd
%    J2Jd = fun_J2Jd(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Dec-2024 14:17:48

J1_1 = in1(1);
J1_2 = in1(4);
J1_3 = in1(7);
J2_1 = in1(2);
J2_2 = in1(5);
J2_3 = in1(8);
J3_1 = in1(3);
J3_2 = in1(6);
J3_3 = in1(9);
t2 = J1_1./2.0;
t3 = J2_2./2.0;
t4 = J3_3./2.0;
J2Jd = reshape([-t2+t3+t4,-J2_1,-J3_1,-J1_2,t2-t3+t4,-J3_2,-J1_3,-J2_3,t2+t3-t4],[3,3]);
end
