/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

int df(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int df_alloc_mem(void);
int df_init_mem(int mem);
void df_free_mem(int mem);
int df_checkout(void);
void df_release(int mem);
void df_incref(void);
void df_decref(void);
casadi_int df_n_out(void);
casadi_int df_n_in(void);
casadi_real df_default_in(casadi_int i);
const char* df_name_in(casadi_int i);
const char* df_name_out(casadi_int i);
const casadi_int* df_sparsity_in(casadi_int i);
const casadi_int* df_sparsity_out(casadi_int i);
int df_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
